# Generated by Django 2.0.5 on 2018-05-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('timestamp', models.DateTimeField(help_text='time this image was created')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('decision', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeratedImage',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='moderator.Image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('decision', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected')], default=2)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moderator.Moderator')),
            ],
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moderator.Image'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moderator.Moderator'),
        ),
    ]
