# Generated by Django 2.0.5 on 2018-05-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_csvData'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
